services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  todo-backend:
    image: napatku/todo101-backend:latest
    ports:
      - "15000:15000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  todo-frontend:
    image: napatku/todo101-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend

volumes:
  mongo_data:
